---
- name: Install Pacman hook tools
  pacman:
    name:
      - pacman-contrib
      - reflector
  become: true

- name: Create pacman hooks directory
  file:
    path: /etc/pacman.d/hooks
    state: directory
  become: true
- name: Deploy pacman hooks
  template:
    src: "{{ item }}"
    dest: /etc/pacman.d/hooks
  with_fileglob: "{{ role_path }}/templates/*.hook"
  become: true

- name: Deploy binaries
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item | basename | splitext | first }}"
    mode: 0755
    force: true
  loop:
    - systemd-boot-config-generator.sh
  become: true
