---
dotfiles:
  - { src: alacritty.yml, dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.yml" }
  - { src: mako, dest: "{{ ansible_user_dir }}/.config/mako/config" }
  - { src: waybar, dest: "{{ ansible_user_dir }}/.config/waybar/config" }
  - { src: swayconfig, dest: "{{ ansible_user_dir }}/.config/sway/config" }
extra_input:
  LongoTech-laptop: |-
    input "2:7:SynPS/2_Synaptics_TouchPad" {
      dwt enabled
      tap enabled
    }
    input "1:1:AT_Translated_Set_2_keyboard" {
      xkb_layout gb
      xkb_variant intl
    }
  longotech-beast: |-
    input "9610:4102:Gaming_KB__Gaming_KB" {
      xkb_layout us
      xkb_variant intl
      xkb_numlock enabled
      xkb_options eurosign:e
    }
extra_output:
  LongoTech-laptop: |-
    output eDP-1 scale 2
