---
- hosts: localhost
  connection: local
  vars_files:
    - settings.yml
  roles:
    - { role: 3d-codecs, tags: ["3d","codec"] }
    - { role: audio, tags: ["audio"] }
    - { role: aur, tags: ["aur"] }
    - { role: bootloader, tags: ["bootloader"] }
    - { role: hooks, tags: ["hooks"] }
    - { role: mkinitcpio, tags: ["mkinitcpio"] }
    - { role: network, tags: ["network"] }
    - { role: pacman, tags: ["pacman"] }
    - { role: passwordless, tags: ["passwordless"] }
    - { role: printing, tags: ["printing"] }
    # Applications
    - { role: apps, tags: ["apps"] }
