---
- name: Install audio tools
  pacman:
    name:
      - cmus
  become: true
- name: Install image editors
  pacman:
    name:
      - gimp
      - gimp-plugin-gmic
      - hugin
      - inkscape
      - luminancehdr
  become: true
- name: Install image tools
  pacman:
    name:
      - imv
  become: true
- name: Install video tools
  pacman:
    name:
      - mpv
      - youtube-dl
  become: true
