---
- name: Install AMD microcode
  pacman:
    name: amd-ucode
  when: "'AuthenticAMD' in ansible_processor"
  become: true
- name: Install Intel microcode
  pacman:
    name: intel-ucode
  when: "'GenuineIntel' in ansible_processor"
  become: true

- name: Configure loader.conf
  template:
    src: loader.conf
    dest: /boot/loader/loader.conf
  become: true

- name: Configure entries
  template:
    src: "{{ item }}"
    dest: /boot/loader/entries
  loop:
    - arch.conf
    - arch-lts.conf
  become: true