---
- name: Install sysadmin apps
  pacman:
    name:
      - ansible
      - ansible-lint
      - terraform
      - vagrant
      - vault
  become: true

- name: Install AUR sysadmin apps
  import_role:
    name: aur
  vars:
    aur_packages:
      # MongoDB
      - robo3t-bin
      - openssl-1.0

- name: Get Vagrant plugin list
  command: vagrant plugin list
  register: command
  changed_when: false

- name: Install Vagrant-libvirt
  command: vagrant plugin install vagrant-libvirt
  when: "'vagrant-libvirt' not in command['stdout']"
