---
- name: Install Git
  pacman:
    name: git
  become: true

- name: Configure Git user name
  git_config:
    name: user.name
    value: "{{ git_name }}"
    scope: global
- name: Configure Git user email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global
